// Externalized main scripts from index.html to avoid inline CSP issues
(function(){
  window.store = {
    products: [], filteredProducts: [], displayedProducts: [], currentPage: 1, productsPerPage: 20, loadedProducts: 0, initialized: false,
    init: function(){ if(typeof window.productsData==='undefined'){ setTimeout(()=>this.init(),500); return; }
      this.products = window.productsData; this.filteredProducts = this.products; this.initialized = true; this.updateCounters(); this.renderProducts(); this.checkURLFilters();
      console.log(`✅ تم تحميل ${this.products.length} منتج بنجاح`);
      console.log(`📊 التفاصيل: ${this.products.filter(p=>p.category==='ساعات').length} ساعة + ${this.products.filter(p=>p.category==='عطور').length} عطر`);
    },
    checkURLFilters:function(){ const urlParams=new URLSearchParams(window.location.search); const category=urlParams.get('category'); const search=urlParams.get('search'); if(category){ filterProducts(category); } if(search){ const si=document.getElementById('searchInput'); if(si){ si.value=search; applyFilters(); } } },
    updateCounters:function(){ const total=this.products.length, watches=this.products.filter(p=>p.category==='ساعات').length, perfumes=this.products.filter(p=>p.category==='عطور').length, featured=this.products.filter(p=>p.featured).length; const up=(id,c)=>{ const el=document.getElementById(id); if(el) el.textContent=`(${c})`; }; up('allCount',total); up('allNavCount',total); up('watchesCount',watches); up('watchesNavCount',watches); up('perfumesCount',perfumes); up('perfumesNavCount',perfumes); up('featuredCount',featured); up('featuredNavCount',featured); },
    renderProducts:function(){ const grid=document.getElementById('productsGrid'); if(!grid) return; if(this.filteredProducts.length===0){ grid.innerHTML=`<div class="no-products"><i class="fas fa-search-minus"></i><h3>لا توجد منتجات مطابقة</h3><p>لم نجد منتجات تطابق معايير البحث الخاصة بك</p><button onclick="resetFilters()" class="btn btn-primary" style="margin-top:1rem;"><i class=\"fas fa-refresh\"></i> إعادة تعيين الفلاتر</button></div>`; return; }
      const toShow=Math.min(this.productsPerPage,this.filteredProducts.length); const arr=this.filteredProducts.slice(0,toShow); this.displayedProducts=arr; this.loadedProducts=toShow; grid.innerHTML=arr.map(p=>this.createProductCard(p)).join(''); this.updateLoadMoreButton(); },
    createProductCard:function(p){ const discount=p.price>(p.salePrice||p.price)?Math.round((p.price-(p.salePrice||p.price))/p.price*100):0; const rating=p.rating||4.5; const reviews=p.reviewsCount||0; return `<article class="product-card" data-product-id="${p.id}" role="gridcell"><div class="product-image"><img src="${p.image}" alt="${p.title}" loading="lazy" onerror="this.src='https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&crop=center'"><div class="product-badges">${discount>0?`<span class=\"product-badge\">خصم ${discount}%</span>`:''}${p.featured?`<span class=\"product-badge featured\">⭐ مميز</span>`:''}</div><div class="product-overlay"><button onclick="event.stopPropagation(); openProductPage('${p.slug}')" class="overlay-btn" title="عرض التفاصيل" aria-label="عرض تفاصيل ${p.title}"><i class="fas fa-eye"></i></button><button onclick="event.stopPropagation(); orderWhatsApp(${p.id})" class="overlay-btn" title="اطلب عبر واتساب" aria-label="اطلب ${p.title} عبر واتساب"><i class="fab fa-whatsapp"></i></button><button onclick="event.stopPropagation(); shareProduct(${p.id})" class="overlay-btn" title="مشاركة" aria-label="مشاركة ${p.title}"><i class="fas fa-share-alt"></i></button></div></div><div class="product-content"><div class="product-meta"><span class="product-category">${p.category}</span><span class="product-brand">${p.brand}</span></div><h3 class="product-title" onclick="openProductPage('${p.slug}')" title="اضغط لعرض التفاصيل">${p.title}</h3><div class="product-rating" role="img" aria-label="تقييم ${rating.toFixed(1)} من 5 نجوم"><div class="stars">${this.generateStars(rating)}</div><div class="rating-info"><span class="rating-number">${rating.toFixed(1)}</span>${reviews>0?`<span class=\"reviews-count\">(${reviews} تقييم)</span>`:''}</div></div><div class="product-pricing"><div class="price-row"><span class="current-price">${p.salePrice||p.price} درهم</span>${p.price>(p.salePrice||p.price)?`<span class=\"original-price\">${p.price} درهم</span>`:''}${discount>0?`<span class=\"savings\">وفر ${p.price-(p.salePrice||p.price)} درهم</span>`:''}</div></div><div class="product-buttons"><a href="/product.html?slug=${p.slug}" target="_blank" rel="noopener" class="btn btn-primary" aria-label="عرض تفاصيل ${p.title}"><i class="fas fa-eye"></i>شاهد التفاصيل</a><button onclick="orderWhatsApp(${p.id})" class="btn btn-whatsapp" aria-label="اطلب ${p.title} عبر واتساب"><i class="fab fa-whatsapp"></i>اطلب الآن</button></div></div></article>`; },
    generateStars:function(r){ const full=Math.floor(r), half=r%1>=0.5; let h=''; for(let i=0;i<full;i++) h+='<i class="fas fa-star" aria-hidden="true"></i>'; if(half) h+='<i class="fas fa-star-half-alt" aria-hidden="true"></i>'; for(let i=0;i<5-full-(half?1:0);i++) h+='<i class="far fa-star" aria-hidden="true"></i>'; return h; },
    updateLoadMoreButton:function(){ const c=document.getElementById('loadMoreContainer'), rem=document.getElementById('remainingCount'); if(!c) return; const total=this.filteredProducts.length, loaded=this.loadedProducts, left=total-loaded; if(left>0){ c.style.display='block'; if(rem) rem.textContent=`متبقي ${left} منتج أخر من أصل ${total} منتج`; } else { c.style.display='none'; } }
  };

  window.openProductPage=function(slug){ const url=`/product.html?slug=${slug}`; window.open(url,'_blank','noopener'); if(typeof gtag!=='undefined'){ const p=window.store.products.find(x=>x.slug===slug); if(p){ gtag('event','view_item',{currency:'AED',value:p.salePrice||p.price,items:[{item_id:p.id,item_name:p.title,item_category:p.category,item_brand:p.brand,price:p.salePrice||p.price,quantity:1}]}); }} };
  window.filterProducts=function(category){ if(!window.store.initialized) return; document.querySelectorAll('.filter-btn').forEach(b=>{ b.classList.remove('active'); if(b.dataset.filter===category){ b.classList.add('active'); }}); let f=[...window.store.products]; if(category==='watches') f=f.filter(p=>p.category==='ساعات'); else if(category==='perfumes') f=f.filter(p=>p.category==='عطور'); else if(category==='featured') f=f.filter(p=>p.featured); const si=document.getElementById('searchInput'); if(si && si.value.trim()){ const term=si.value.trim().toLowerCase(); f=f.filter(p=>p.title.toLowerCase().includes(term)||p.brand.toLowerCase().includes(term)||(p.description&&p.description.toLowerCase().includes(term))); } window.store.filteredProducts=f; window.store.loadedProducts=0; window.store.renderProducts(); const url=new URL(window.location); if(category!=='all') url.searchParams.set('category',category); else url.searchParams.delete('category'); window.history.replaceState({},'',url); if(typeof gtag!=='undefined'){ gtag('event','filter_products',{filter_category:category,results_count:f.length}); } };
  window.applyFilters=function(){ const b=document.querySelector('.filter-btn.active'); const c=b?b.dataset.filter:'all'; filterProducts(c); };
  window.resetFilters=function(){ const si=document.getElementById('searchInput'); if(si) si.value=''; filterProducts('all'); const url=new URL(window.location); url.search=''; window.history.replaceState({},'',url); };
  window.loadMoreProducts=function(){ const btn=document.getElementById('loadMoreBtn'); if(!btn) return; const orig=btn.innerHTML; btn.innerHTML='<i class="fas fa-spinner fa-spin"></i> جاري التحميل...'; btn.disabled=true; setTimeout(()=>{ const grid=document.getElementById('productsGrid'); const total=window.store.filteredProducts.length; const loaded=window.store.loadedProducts; const next=Math.min(window.store.productsPerPage,total-loaded); if(next>0){ const nextArr=window.store.filteredProducts.slice(loaded,loaded+next); const html=nextArr.map(p=>window.store.createProductCard(p)).join(''); grid.insertAdjacentHTML('beforeend',html); window.store.loadedProducts+=next; window.store.displayedProducts=[...window.store.displayedProducts,...nextArr]; window.store.updateLoadMoreButton(); if(typeof gtag!=='undefined'){ gtag('event','load_more_products',{loaded_count:next,total_loaded:window.store.loadedProducts}); } } btn.innerHTML=orig; btn.disabled=false; },800); };
  window.orderWhatsApp=function(id){ const p=window.store.products.find(x=>x.id===parseInt(id)); if(!p) return; const msg=`مرحباً 👋\n\n🛍️ أريد طلب هذا المنتج من متجر هدايا الإمارات:\n\n📦 *${p.title}*\n💰 السعر: *${p.salePrice||p.price} درهم* (شامل الشحن المجاني)\n🏷️ الفئة: ${p.category}\n🏪 العلامة التجارية: ${p.brand}\n⭐ التقييم: ${p.rating?p.rating.toFixed(1):'جديد'}/5\n\n🔗 رابط المنتج: ${window.location.origin}/product.html?slug=${p.slug}\n\nشكراً لكم ❤️ 🇦🇪`; window.open(`https://wa.me/201110760081?text=${encodeURIComponent(msg)}`,'_blank'); if(typeof gtag!=='undefined'){ gtag('event','begin_checkout',{currency:'AED',value:p.salePrice||p.price,items:[{item_id:p.id,item_name:p.title,item_category:p.category,item_brand:p.brand,price:p.salePrice||p.price,quantity:1}]}); } };
  window.shareProduct=function(id){ const p=window.store.products.find(x=>x.id===parseInt(id)); if(!p) return; const data={title:`${p.title} - متجر هدايا الإمارات 🇦🇪`,text:`اكتشف ${p.title} بسعر ${p.salePrice||p.price} درهم مع شحن مجاني في الإمارات`,url:`${window.location.origin}/product.html?slug=${p.slug}`}; if(navigator.share){ navigator.share(data); } else { const text=`${data.text}\n${data.url}`; if(navigator.clipboard){ navigator.clipboard.writeText(text).then(()=>{ showNotification('تم نسخ رابط المنتج بنجاح! 📋','success'); }); } } };
  window.showNotification=function(message,type='success'){ const n=document.createElement('div'); n.className=`notification ${type}`; n.style.cssText='position:fixed;top:20px;right:20px;background:white;padding:1rem 1.5rem;border-radius:.5rem;box-shadow:var(--shadow-xl);border-left:4px solid '+(type==='success'?'var(--success)':'var(--danger)')+';z-index:10000;transform:translateX(400px);opacity:0;transition:all .3s ease;max-width:300px;'; n.innerHTML=`<div style="display:flex;align-items:center;gap:.5rem;"><i class="fas fa-${type==='success'?'check-circle':'exclamation-circle'}" style="color:${type==='success'?'var(--success)':'var(--danger)'};"></i><span>${message}</span></div>`; document.body.appendChild(n); setTimeout(()=>{ n.style.transform='translateX(0)'; n.style.opacity='1'; },100); setTimeout(()=>{ n.style.transform='translateX(400px)'; n.style.opacity='0'; setTimeout(()=>n.remove(),300); },4000); };

  document.addEventListener('DOMContentLoaded',function(){ const si=document.getElementById('searchInput'); if(si){ let t; si.addEventListener('input',function(){ clearTimeout(t); t=setTimeout(()=>{ const url=new URL(window.location); if(this.value.trim()){ url.searchParams.set('search',this.value.trim()); }else{ url.searchParams.delete('search'); } window.history.replaceState({},'',url); applyFilters(); if(typeof gtag!=='undefined' && this.value.trim()){ gtag('event','search',{search_term:this.value.trim()}); } },300); }); si.addEventListener('keypress',e=>{ if(e.key==='Enter'){ applyFilters(); } }); }
    setTimeout(()=>{ window.store.init(); console.log('✨ المتجر جاهز بكامل المنتجات والمميزات!'); showNotification('مرحباً بك في متجر هدايا الإمارات! 🇦🇪','success'); },1000);
  });
})();